### ISSUE TITLE
Story: Create OpenAPI specification for API v3

### ISSUE THREAD

**Issue by cutwater** [ansible/galaxy-dev#29]
Create OpenAPI specification documents that describes Automation Hub public API version 3.

## Requirements

- OpenAPI specification document should be in YAML format.
- API endpoints and schemas should have common structure and fields order.
- Specification should be structured to be reviewable and editable by human.

## Action items

- [x] Create minimal specification #30
- [x] Define pagination schemas #31
- [x] Define error schemas #32
- [x] Define Namespace schemas #33
- [x] Define Collection schemas #34
- [x] Define Collection Import schemas #35
- [x] Define User \ Profile schemas #36
- [x] Remove namespace creation and deletion from API
- [x] API: For Collections, update the Public schema and add a _ui schema #55
- [x] API: Add Collection Version schema #56 

### Namespaces

  1. List namespaces
     `GET /namespaces/`

  2. ~~Create namespace
     `POST /namespaces/`~~

  3. Get namespace details
     `GET /namespaces/{name}/`

  4. Update namespace
     `PUT /namespaces/{name}/`

  5. ~~Delete namespace
     `DELETE /namespaces/{name}/`~~

  6. ~~List collections in namespace
     `GET /namespaces/{name}/collections/`~~

  7. ~~List collection import tasks for namespace
     `GET /namespaces/{name}/imports/collections/`~~

### Collections

  1. Upload a collection
     `POST /collections/`

  2. List collections
     `GET /collections/`

  3. Get a collection details
     `GET /collections/{namespace}/{name}/`

  4. Update collection details
     `PUT /collections/{namespace}/{name}/`

  5. List collection versions
     `GET /collections/{namespace}/{name}/versions/`

  6. Get a collection version details
     `GET /collections/{namespace}/{name}/versions/{version}/`

  7. Get a collection artifact detail
     `GET /collections/{namespace}/{name}/versions/{version}/artifact/`

### Search

  1. Search collections
     `GET /search/collections/`

  2. Search tags
     `GET /search/tags/`

### Imports

  1. Get import details
     `GET /imports/collections/{task_id}/`

### Downlods

  1. Download collection artifact
     `GET /downloads/collections/{filename}`

### Users

  1. List Users
     `GET /users/`

  2. Get User
     `GET /users/{id}/`

### Profile

  1. Get Profile
     `GET /profile/`

**Comment by cutwater** [comment]
The following API endpoints are removed as they can be implemented by using filters.
>   6. List collections in namespace
>      `GET /namespaces/{name}/collections/`~~
> 
>   7. ~~List collection import tasks for namespace
>      `GET /namespaces/{name}/imports/collections/`

**Comment by newswangerd** [comment]
What is a profile?

**Comment by cutwater** [comment]
@newswangerd Profile is a better naming for `/me`. It returns current user profile.

**Comment by newswangerd** [comment]
@cutwater I think we basically decided today that namespace creation is going to happen in the django admin, so we can get rid of the create namespace API

**Comment by chouseknecht** [comment]
Needs final review after AnsibleFest
