### ISSUE TITLE
Story: Implement database models

### ISSUE THREAD

**Issue by cutwater** [ansible/galaxy-dev#39]
Implement database models required for API. 
Models implementation should assume that some data is delegated to be stored in Pulp service.

Action items:

- [x] Implement user models (#40).
- [x] Implement basic namespace models (#47).
- [x] Implement namespace resource page models.
- [x] Add database support for #63. (#65)
- ~~Implement collection models.~~
