### ISSUE TITLE
Story: Galaxy API v3

### ISSUE THREAD

**Issue by cutwater** [ansible/galaxy-dev#48]
Action items:

- [x] Implement custom error handling (#49).
- [x] Implement custom pagination (#50).
- [x] Implement collection endpoints (#52).

UI:
- [x] Implement namespaces endpoints (#51).
- [x] Implement collection endpoints (#75).
- [x] Implement collection imports endpoints (#53).
- [x] Implement download endpoints (#54).
