### ISSUE TITLE
Client: Modify ansible-galaxy to work with v3

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy-dev#60]
Make `ansible-galaxy` v3 aware, so that it can publish and download to Automation Hub. Not sure if we'll need to do anything special as far as authentication. 

Has to be done before 29-August, Ansible 2.9 code freeze. Assuming @alikins can knock this out upon return from vacation.

**Comment by chouseknecht** [comment]
Also, confirm that `ansible-galaxy` is able to perform token authentication with both Community Galaxy and Automation Hub.

**Comment by chouseknecht** [comment]
Address https://github.com/ansible/ansible/issues/60316

**Comment by alikins** [comment]
Some notes:

- [ ] will be dependent on ansible-galaxy supporting multiple galaxy api servers. 
  - [ ] ansible-galaxy collections install -r requirements.yml to support multiple servers https://github.com/ansible/ansible/issues/60316
    - [ ]  ansible-galaxy - define multiple galaxy instances in ansible.cfg PR from @jborean93 at https://github.com/ansible/ansible/pull/60553
- [ ] will depend on #54 - API: Implement collection download endpoints
- [ ] will depend on #53 - API: Implement collection imports endpoints.

Community Galaxy and Automation Hub API differences
- pagination differences as described at https://petstore.swagger.io/?url=https://raw.githubusercontent.com/ansible/galaxy-api/master/openapi/openapi.yaml under the 'Pagination' description.
- error responses differences  https://petstore.swagger.io/?url=https://raw.githubusercontent.com/ansible/galaxy-api/master/openapi/openapi.yaml under the 'Pagination' description.
- API URL collection endpoints use `/api/v3` instead of `/api/v2`
- Particular end point differences
  - [ ] Response object of `GET /api/v3/collections/{namespace}/{name}/versions/{version}` (https://petstore.swagger.io/?url=https://raw.githubusercontent.com/ansible/galaxy-api/master/openapi/openapi.yaml#/Collections/getCollectionVersions) is different from the v2 version. https://github.com/ansible/galaxy-api/commit/6e5bf1b7683c71b4d4261cd92b749d484ca6e41d#diff-61d421c52ac59775eb29fb236d3d6f5a has the change.

**Comment by alikins** [comment]
Currently, ansible-galaxy, even with https://github.com/ansible/ansible/pull/60553, only supports using the first defined galaxy server for 'publish' and 'login'. I haven't include plans for adding support for specifying[1] which galaxy server to publish/login to in https://github.com/ansible/galaxy-dev/issues/60 yet.     

 [1] Our I guess, maybe trying all of them, though that seems odd.

**Comment by alikins** [comment]
Update: v3 API is switching back to LimitOffset style pagination
